name: MSVC build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: Integrate vcpkg
      run: vcpkg integrate install
    - name: Build vcpkg libraries
      run: vcpkg install freetype glfw3 capstone[arm,arm64,x86] --triplet x64-windows-static
    - name: Profiler GUI Debug
      run: msbuild .\profiler\build\win32\Tracy.vcxproj /property:Configuration=Debug /property:Platform=x64
    - name: Profiler GUI Release
      run: msbuild .\profiler\build\win32\Tracy.vcxproj /property:Configuration=Release /property:Platform=x64
    - name: Update utility
      run: .\update\build\win32\update.vcxproj /property:Configuration=Debug /property:Platform=x64
    - name: Capture utility
      run: msbuild .\capture\build\win32\capture.vcxproj /property:Configuration=Debug /property:Platform=x64
    - name: Library
      run: msbuild .\library\win32\TracyProfiler.vcxproj /property:Configuration=Release /property:Platform=x64
